/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:49bd62e2-265c-4bab-b929-51e2288e8dfd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Tb2RMkHuV",
    "aws_user_pools_web_client_id": "4v6ulh0e6o7d9r6qdnpk8142qu",
    "oauth": {}
};


export default awsmobile;
